<template>
  <div id="articleContent" class="ajaxed-in">
    <h2>Pour en apprendre davantage</h2>
    <h3>Livres de bibliothèque</h3>
    <p>Si vous aimeriez en apprendre davantage sur le thème de la salle de classe virtuelle, les livres sont disponibles à la bibliothèque de l'EFPC. Vous pouvez faire une réservation en cliquant sur les liens vers le catalogue ci-dessous.</p>
    <ul class="fa-ul">
      <li> 🕮 <span>Potvin, Claude, Thomas Michael Power, and Anne Ronchi. 2014.</span> <em><a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A%2F%2F10.128.0.45%3A8080%2Ffr.htm&TN=Catalog&SN=AUTO29812&Se=444&RN=0&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=11953&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"> La formation en ligne les conseillers et ingénieurs pédagogiques : 20 études de cas. [Paris]: Hermann.</a></em> [Paris]: Hermann.<br> ISBN 9782763720975 </li>
      <li> 🕮 <span>Christopher, Darlene. 2015. </span><em><a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A%2F%2F10.128.0.45%3A8080%2F&TN=Catalog&SN=AUTO9865&Se=388&RN=0&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=11898&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank">The successful virtual classroom: how to design and facilitate interactive and engaging live online learning.</a></em> New York : AMACON.<br> ISBN 9780814434284 </li>
      <li> 🕮 <span>Huggett, Cindy. 2013.</span> <em><a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A%2F%2F10.128.0.45%3A8080%2F&TN=Catalog&SN=AUTO9933&Se=389&RN=1&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=11611&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"> The virtual training guidebook how to design, deliver, and implement live online learning. Alexandria, VA: ASTD Press.</a></em> Alexandria, VA: ASTD Press.<br> ISBN 9781562868611 </li>
      <li> 🕮 <span>Turmel, Wayne. 2011.</span> <em><a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A%2F%2F10.128.0.45%3A8080%2F&TN=Catalog&SN=AUTO10012&Se=390&RN=1&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=10169&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"> 10 steps to successful virtual presentations. Alexandria, Va: ASTD Press.</a></em> Alexandria, VA : ASTeD Press.<br> ISBN 9781562867461 </li>
      <li> 🕮 <span>Pluth, Becky Pike. 2010.</span> <em><a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A%2F%2F10.128.0.45%3A8080%2F&TN=Catalog&SN=AUTO10097&Se=391&RN=0&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=10085&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"> Webinars with wow factor: tips, tricks & interactivities for virtual training. excelsior, Minn: Pluth Consulting.</a></em> excelsior, Minn: Pluth Consulting.<br> ISBN 9780979410314 </li>
    </ul>
    <h3>Livres numériques</h3> Voici une liste des livres numériques recommandées, disponibles à partir de la cyber-bibliothèque de l'EFPC. Cliquez sur un lien pour consulter le livre numérique à partir de votre navigateur ou pour le télécharger sur votre ordinateur ou sur votre tablette pour une période d'une semaine. Veuillez noter que vous aurez besoin de l'application Bluefire Reader afin de télécharger sur votre tablette ou téléphone intelligent. <ul class="fa-ul">
      <li> <span class="fa fa-book fa-li" /> Clark, R. C., Kwinn, A.<em><a href="//search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=190525&site=ehost-live" target="_blank">The New Virtual Classroom: evidence-based Guidelines for Synchronous e-Learning.</a></em> San Francisco : Wiley, 2007. </li>
      <li> <span class="fa fa-book fa-li" /> Christopher, D., Huder, K. <em><a href="//search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=795566&site=ehost-live" target="_blank"> The Successful Virtual Classroom : How to Design and Facilitate Interactive and engaging Live Online Learning</a></em>. American Management Association, Amacom Division, 2015. </li>
      <li> <span class="fa fa-book fa-li" /> Palloff, R.M., Pratt, K.<em><a href="//search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=588005&site=ehost-live" target="_blank"> Lessons From the Virtual Classroom : The Realities of Online Teaching</a></em>. John Wiley &amp; Sons, Inc., 2013. </li>
      <li><span class="fa fa-book fa-li" /> Stevenson, Nancy. <em><a href="//search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=128120&site=ehost-live" target="_blank">WebEx Web Meetings for Dummies.</a></em> John Willey &amp; Sons, Inc., 2005. <strong /> </li>
    </ul>
    <h3>Ressources en ligne</h3> Si vous souhaitez savoir plus sur la salle de classe virtuelle, les ressources en ligne suivantes sont recommandées. <ul class="fa-ul">
      <li> <a href="//fr.netvisio.com/wp-content/uploads/2013/09/Classe-virtuelle-Bonnes-pratiques.pdf" target="_blank">Classe Virtuelle 10 bonnes pratiques</a> </li>
      <li> <a href="//apprentissageenligne.ca/sites/default/files/public-resources/la_salle_de_classe_en_ligne_les_5_meilleurs_outils_mars_2013.pdf" target="_blank">La salle de classe en ligne de l'Apprentissage en ligne : les cinq meilleurs outils pour l'engagement des apprenantes et apprenants.</a> (Apprentissageenligne.ca) </li>
      <li> <a href="http://www.cefrio.qc.ca/uploads/Classes_virtuelles_lecons_cas_Qc.pdf" target="_blank">La classe virtuelle : quelques leçons tirées de cas du Québec et d'ailleurs</a> (CeFRIO) </li>
      <li><a href="//university.webex.com/training/student/content/welcome.do" target="_blank">Tutoriels et Ressources</a> (Université WebEx) </li>
      <li> <a href="//www.cisco.com/c/dam/en/us/td/docs/collaboration/training_center/wx_tc_host_ug.pdf" target="_blank">Training Centre User Guide</a> (Cisco WebEx) </li>
      <li> <a href="http://www.intercall.com/files/Meeting_Center_User_Guide.pdf" target="_blank">Meeting Centre User Guide</a> (Cisco WebEx) </li>
      <li> <a href="//gcconnex.gc.ca/groups/profile/5748531/the-wonderful-world-of-webex-le-merveilleux-monde-de-webex" target="_blank">Community for Government of Canada WebEx users: The Wonderful World of WebEx</a> (GCconnex Group) </li>
      <li> <a href="http://www.gcpedia.gc.ca/wiki/GTS_WebEx" target="_blank">Government Teleconferencing Services / Web Conference WebEx</a> (Service partages Canada) </li>
      <li> <a href="//collabhelp.cit.cornell.edu/web-classroom-with-webex/" target="_blank">Web Classroom with WebEx</a> (Cornell University) </li>
      <li><a href="//img.en25.com/Web/GovDeliveryInc/%7B81d42c5d-6731-4204-9985-c909f58e4b5d%7D_Guide-Virtual-events.pdf?elq=%7e%7eeloqua..type--emailfield..syntax--recipientid%7e%7e&amp;elqCampaignId=%7e%7eeloqua..type--campaign..campaignid--0..fieldname--id%7e%7e" target="_blank">Building Better Conferences and Training: The Value of Virtual events in Government.</a> (The GovLoop)</li>
    </ul>
  </div>
</template>
