<template>
  <div id="articleContent" class="ajaxed-in">
    <h2>Determining Topics or Threads<br></h2>

    <p>
      Choice of topics or threads should be related to the learning outcomes expected from discussion. &nbsp;Discussion topics will always
      generate more student participation if they are either linked to assessment, assignments or have strong intrinsic interest for the
      students. Topics can be generated by the instructor or by the students themselves.<br>
      <br>
      Topics must be chosen and worded in such a way as to encourage discussion. Topics for instance that suggest there is a 'right' answer
      or 'best' way to do things, or merely require students to repeat materials in the course, are 'dead-enders', in that once an
      appropriate response has been made by one or two students, there is little more to add.<br>
      There are at several ways you could use structure topics or threads in a discussion forum:
    </p>

    <ul>
      <li>
        <strong>assignment-related</strong>: this kind of topic is, or could be, directly related to an assignment, but is not the
        assignment itself. Thus the topic may provide the opportunity for students to discuss aspects of an assignment or to complete part
        of an assignment. For instance, if the assignment requires students to work on a project, one discussion topic could be about the
        framework or outline of a project. If there are important concepts that need to be dealt with in an assignment, then students could
        be given a case or exercise and be asked to apply the concepts to the case or example. Thus, if students have been taught how to do
        a business plan, they might be asked to discuss the best way to do market research on a particular proposal, while the assignment
        requires a full business plan to be developed, incorporating market research. The discussion forum may be used to facilitate
        discussion on a group assignment.<br>
      </li>

      <li>
        <strong>assessment-based:</strong> for example, a group of students can be given a problem to solve. The discussion forum
        records their discussion of the problem and the processes they use to solve it, and students are assessed on both the outcome and
        the process of solving the problem.<br>
      </li>

      <li>
        <strong>interest-based:</strong> This kind of topic is not directly related to the assignment but one that generates a lot of
        interest in students. For instance, students may want to discuss recent events that relate to the course but may not be one of the
        main topics of the course.
      </li>
    </ul>
  </div>
</template>
