<template>
  <div id="articleContent" class="ajaxed-in">
    <h2>Les Droits d'auteur : Pour en apprendre davantage </h2> Si vous aimeriez en apprendre davantage sur le thème des blogues, les livres sont disponibles à la bibliothèque de l'EFPC. Vous pouvez faire une réservation en cliquant sur les liens vers le catalogue ci-dessous. <ul class="fa-ul">
      <li>🕮 Baribeau, Marc, Patrick Gingras, and Sylvain Gadoury. 2013. <a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A//10.128.0.45%3A8080/fr.htm&TN=Catalog&SN=AUTO25817&Se=429&RN=0&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=12080&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"><em>Principes généraux de la Loi sur le droit d'auteur</em></a>. Québec: Les Publications du Québec.</li>
      <li>🕮 Harris, Lesley ellen. 2014. <a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A//10.128.0.45%3A8080/&TN=Catalog&SN=AUTO10232&Se=360&RN=0&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=11508&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"><em>Canadian copyright law</em></a>.</li>
      <li>🕮 Miller, Joyce L., and C. Daniel Miller. 2013. <a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A//10.128.0.45%3A8080/fr.htm&TN=Catalog&SN=AUTO17429&Se=376&RN=0&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=11957&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"><em>Copyright clearance for creatives: a guide for independent publishers and their support providers</em></a>.</li>
      <li>🕮 Murray, Laura Jane, and Samuel e. Trosow. 2013. <a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A//10.128.0.45%3A8080/&TN=Catalog&SN=AUTO10915&Se=365&RN=0&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=11663&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"><em>Canadian copyright: a citizen's guide</em></a>. Toronto: Between the Lines.</li>
      <li>🕮 Geist, Michael. 2013. <a href="//10.128.0.45:8080/ics-wpd/exec/icswppro.dll?AC=GeT_ReCORD&XC=/ics-wpd/exec/icswppro.dll&BU=http%3A//10.128.0.45%3A8080/&TN=Catalog&SN=AUTO10232&Se=360&RN=2&MR=20&TR=0&TX=1000&eS=0&CS=1&XP=&RF=Brief+French&eF=&DF=Full+French&RL=1&eL=0&DL=0&NP=2&ID=&MF=WPFreMsg.ini&MQ=&TI=0&DT=&ST=0&IR=11664&NR=0&NB=0&SV=0&SS=0&BG=ffffff&FG=000000&QS=default_new&OeX=ISO-8859-1&OeH=ISO-8859-1" target="_blank"><em>The copyright pentalogy: how the Supreme Court of Canada shook the foundations of Canadian copyright law</em></a>.</li>
    </ul>
    <h3>Ressources en ligne</h3>
    <p>Si vous souhaitez savoir plus sur les droits d'auteur, les ressources en ligne suivantes sont recommandées. </p>
    <ul>
      <li><a href="//recherche.uqac.ca/wp-content/uploads/20../../guide_droits_auteur.pdf<" target="_blank">Guide sur les droits d'auteur: Un guide destiné aux professeurs et aux chercheurs en milieu universitaire</a>. RUTTeQ et ValoRIST, (2010)</li>
      <li><a href="//pch.gc.ca/fra/1274367970108/1288796690102" target="_blank">Glossaire des termes de droit d'auteur</a> (Patrimoine canadien) </li>
      <li><a href="http://www.ic.gc.ca/app/opic-cipo/cpyrghts/dsplySrch.do?lang=fra" target="_blank">Base de données sur les droits d'auteur canadiens</a> (Industrie Canada) </li>
      <li><a href="http://www.ic.gc.ca/eic/site/cipointernet-internetopic.nsf/fra/h_wr02281.html" target="_blank">Le guide du droit d'auteur</a> (Office de la propriété intellectuelle du Canada) </li>
      <li><a href="//library.concordia.ca/help/copyright/?guid=fdvsfu" target="_blank">Le guide du droit d'auteur</a> (L'Université de Concordia) </li>
      <li><a href="//support.google.com/youtube/answer/2797449?hl=fr" target="_blank">Questions générales sur les droits d'auteur</a> (YouTube/Aide Google) </li>
      <li><a href="http://www.mheducation.ca/companion/copyrightlaw/inside_the_book.php" target="_blank">Canadian Copyright Law</a> (The McGraw-Hill Ryerson Companies Companion Site) </li>
      <li><a href="http://www.edweek.o../../articles/20../../23/02openlicense_web.h02.html" target="_blank">Open-Content Licencing</a> (education Week Digital Directions)</li>
      <li><a href="//creativecommons.org/education" target="_blank">Open educational resources</a> (Creative Commons) </li>
    </ul>
  </div>
</template>
