<template>
  <div id="articleContent" class="ajaxed-in">
    <h2>Obligations de langues officielles pour GCconnex et GCpédia</h2>
    <h3>Blogues/&#8203;Forums contenu libre</h3>
    <p>Règles concernant les langues officielles<sup><a href="#_ftnref1">[1]</a></sup>&nbsp;:</p>
    <ul>
      <li>Les règles qui s'appliquent à tous les aspects de votre travail s'appliquent aussi aux outils GC2.0, ainsi qu'aux plateformes d'apprentissage en ligne utilisées dans l'écosystème, telles que Moodle. Les documents ou l'information que vous feriez normalement traduire en vue d'en faire la diffusion par courriel ou d'en remettre des copies papier devraient aussi être traduits pour être présentés dans les outils GC2.0. GCpédia et GCconnex <em>ne sont pas</em> des moyens de vous soustraire à vos obligations en matière de langues officielles&nbsp;: toutes les politiques valides dans le mode «&nbsp;hors ligne&nbsp;» s'appliquent «&nbsp;en ligne&nbsp;».</li>
      <li>Les employés travaillant dans des régions désignées bilingues aux fins de la langue de travail sont libres d'utiliser la langue officielle de leur choix, et ce, dans toutes les sphères de leur travail, y compris dans les outils GC2.0 et sur les plateformes d'apprentissage. Par exemple, si vous avez une page/&#8203;section en français et une page/&#8203;section en anglais où vous invitez les employés à s'exprimer, l'une ne sera pas la copie parfaite de l'autre et cela est tout à fait légitime. Bien qu'il ne soit pas obligatoire de faire traduire les ébauches et documents de travail, il est fortement recommandé de le faire, puisqu'en vertu de la partie&nbsp;V de la <em>Loi sur les langues officielles</em>, les employés travaillant dans les régions ou secteurs désignés bilingues ont le droit de travailler dans la langue officielle de leur choix. Les versions définitives des documents doivent obligatoirement être offertes dans les deux langues officielles.</li>
      <li>Il faut aussi savoir que les fonctionnaires n'ont pas tous les mêmes obligations en matière de langues officielles. Par exemple, les fonctionnaires de régions unilingues peuvent verser du contenu sur GCpédia et GCconnex dans une seule langue. encore une fois, la même règle s'applique «&nbsp;en ligne&nbsp;» et «&nbsp;hors ligne&nbsp;».</li>
      <li>Dans le cas de la tenue d'un blogue ou forum bilingue, il est recommandé que le modérateur fournisse régulièrement, dans les deux langues officielles, un sommaire des commentaires déposés ou des discussions qui ont eu lieu.<sup><a href="#_ftnref2">[2]</a></sup> Afin d'encourager l'usage des deux langues officielles, le modérateur devrait donner l'exemple en s'exprimant dans les deux langues si possible, et demander l'aide d'un coorganisateur au besoin.</li>
      <li>Il est important de bien faire la distinction entre les droits linguistiques des employés et les obligations linguistiques de l'École en tant qu'organisation. Lorsqu'un employé soumet un commentaire ou une information en son nom dans un forum en ligne, il est encouragé à le faire dans la langue de son choix. Toutefois, lorsque le commentaire ou l'information sont diffusés au nom de l'École ou de la fonction de l'employé au sein de l'École, cela doit être fait dans les deux langues officielles. Si l'information fournie provient de l'organisation, il convient de rediriger les utilisateurs vers le site Web où le contenu est affiché dans les deux langues.</li>
    </ul>
    <p><a id="_ftnref1">[1]</a>&nbsp;Voir <a href="http://www.gcpedia.gc.ca/wiki/FAQ_sur_les_Outils_GC2.0" target="_blank">FAQ sur les Outils GC2.0</a>.</p>
    <p><a id="_ftnref2">[2]</a>&nbsp;Pour plus de renseignements, consultez la <a href="http://www.tbs-sct.gc.ca/pol/doc-fra.aspx?id=27517" target="_blank">Ligne directrice sur l'utilisation officielle des médias sociaux&nbsp;&ndash; Annexe&nbsp;A</a>.</p>
  </div>
  </body>
<!-- Instanceend -->
</template></html>
